using SQLite;
using System;

namespace JournalNote.Models
{
    // Represents a journal entry stored in the database
    [Table("journal_entries")]
    public class JournalEntry
    {
        // Unique ID for each entry, auto-generated by database
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }

        // Date in yyyy-MM-dd format (e.g., "2026-01-27")
        // Unique ensures only one entry per day
        [Unique]
        public string Date { get; set; } = string.Empty;

        // Entry title (max 200 characters)
        [MaxLength(200)]
        public string Title { get; set; } = string.Empty;

        // Main journal content (HTML from rich text editor)
        public string Content { get; set; } = string.Empty;

        // ID of the main mood (e.g., Happy, Sad)
        // Nullable because it's optional
        public int? PrimaryMoodId { get; set; }

        // Additional mood IDs stored as "1,3,5" format
        // Multiple moods separated by commas
        public string SecondaryMoodIds { get; set; } = string.Empty;

        // Tag IDs stored as "2,4,6" format
        // Used to categorize entries
        public string TagIds { get; set; } = string.Empty;

        // Optional category for the entry (e.g., "Personal", "Work")
        public string Category { get; set; } = string.Empty;

        // When the entry was first created
        public DateTime CreatedAt { get; set; }

        // When the entry was last updated
        public DateTime UpdatedAt { get; set; }

        // Constructor - sets up default values for new entries
        public JournalEntry()
        {
            CreatedAt = DateTime.Now;
            UpdatedAt = DateTime.Now;
            Date = DateTime.Today.ToString("yyyy-MM-dd");
        }
    }
}